export const data = [
  {
    id: 1,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 2,
    country: "France",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 3,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 4,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 5,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 6,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 7,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 8,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 9,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 10,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 11,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 12,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 13,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 14,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 15,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 16,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 17,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 18,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 19,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
  {
    id: 20,
    country: "United States",
    rank: "1",
    rankColored: "(+2)",
    Interest: "43MM",
    InterestColred: "(-5MM)",
    Influencers: "805",
  },
];
