export const SET_FILTERS = 'SET_FILTERS';
export const UPDATE_LOADERS = 'UPDATE_LOADERS';
export const UPDATE_ALL_LOADERS_TRUE = 'UPDATE_ALL_LOADERS_TRUE';
export const RESET_FILTERS = 'RESET_FILTERS';
